name: consumindo_api
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  get: ^4.6.5
  money2: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/doge_image.png
    - assets/imagens-moedas/AUD.png
    - assets/imagens-moedas/BRL.png
    - assets/imagens-moedas/CAD.png
    - assets/imagens-moedas/CHF.png
    - assets/imagens-moedas/CNY.png
    - assets/imagens-moedas/CZK.png
    - assets/imagens-moedas/EUR.png
    - assets/imagens-moedas/GBP.png
    - assets/imagens-moedas/INR.png
    - assets/imagens-moedas/JPY.png
    - assets/imagens-moedas/KRW.png
    - assets/imagens-moedas/NZD.png
    - assets/imagens-moedas/PLN.png
    - assets/imagens-moedas/RUB.png
    - assets/imagens-moedas/TRY.png
    - assets/imagens-moedas/TWD.png
    - assets/imagens-moedas/USD.png
